apiVersion: apps/v1
kind: Deployment
metadata:
  name: switch
spec:
  template:
    spec:
      initContainers:
        - name: appconfig-agent
          env:
            - name: MANIFEST
              value: "switch:dev:manifest"
      containers:
        - name: switch
          env:
            - name: APP_VERSION
              value: "v1"
